from datetime import timedelta

from upstox_api.api import *

upstox = Upstox('7QQDdOIHNxatXDiRIHbyv2sG3J8QOozU7o8UYKmu', '1705a27db85f6e0a703de1a3f7207507661de2d9')
upstox.get_master_contract('NSE_EQ')  # get contracts for NSE FO
fno_stock_list = {'ACC',
                  'ADANIENT',
                  'ADANIPORTS',
                  'ADANIPOWER',
                  'AJANTPHARM',
                  'ALBK',
                  'AMARAJABAT',
                  'AMBUJACEM',
                  'ANDHRABANK',
                  'APOLLOHOSP',
                  'APOLLOTYRE',
                  'ARVIND',
                  'ASHOKLEY',
                  'ASIANPAINT',
                  'AUROPHARMA',
                  'AXISBANK',
                  'AUTO',
                  'BAJAJFINSV',
                  'BAJFINANCE',
                  'BALKRISIND',
                  'BALRAMCHIN',
                  'BANKBARODA',
                  'BANKINDIA',
                  'BATAINDIA',
                  'BEL',
                  'BEML',
                  'BERGEPAINT',
                  'BHARATFIN',
                  'BHARATFORG',
                  'BHARTIARTL',
                  'BHEL',
                  'BIOCON',
                  'BOSCHLTD',
                  'BPCL',
                  'BRITANNIA',
                  'CADILAHC',
                  'CANBK',
                  'CANFINHOME',
                  'CAPF',
                  'CASTROLIND',
                  'CEATLTD',
                  'CENTURYTEX',
                  'CESC',
                  'CGPOWER',
                  'CHENNPETRO',
                  'CHOLAFIN',
                  'CIPLA',
                  'COALINDIA',
                  'COLPAL',
                  'CONCOR',
                  'CUMMINSIND',
                  'DABUR',
                  'DALMIABHA',
                  'DCBBANK',
                  'DHFL',
                  'DISHTV',
                  'DIVISLAB',
                  'DLF',
                  'DRREDDY',
                  'EICHERMOT',
                  'ENGINERSIN',
                  'EQUITAS',
                  'ESCORTS',
                  'EXIDEIND',
                  'FEDERALBNK',
                  'FORTIS',
                  'GAIL',
                  'GLENMARK',
                  'GMRINFRA',
                  'GODFRYPHLP',
                  'GODREJCP',
                  'GODREJIND',
                  'GRANULES',
                  'GRASIM',
                  'GSFC',
                  'HAVELLS',
                  'HCC',
                  'HCLTECH',
                  'HDFC',
                  'HDFCBANK',
                  'HDIL',
                  'HEROMOTOCO',
                  'HEXAWARE',
                  'HINDALCO',
                  'HINDPETRO',
                  'HINDUNILVR',
                  'HINDZINC',
                  'IBULHSGFIN',
                  'ICICIBANK',
                  'ICICIPRULI',
                  'ICIL',
                  'IDBI',
                  'IDEA',
                  'IDFC',
                  'IDFCBANK',
                  'IFCI',
                  'IGL',
                  'INDIACEM',
                  'INDIANB',
                  'INDIGO',
                  'INDUSINDBK',
                  'INFIBEAM',
                  'INFRATEL',
                  'INFY',
                  'IOC',
                  'IRB',
                  'ITC',
                  'JETAIRWAYS',
                  'JINDALSTEL',
                  'JISLJALEQS',
                  'JPASSOCIAT',
                  'JSWENERGY',
                  'JSWSTEEL',
                  'JUBLFOOD',
                  'JUSTDIAL',
                  'KAJARIACER',
                  'KOTAKBANK',
                  'KPIT',
                  'KSCL',
                  'KTKBANK',
                  'TFH',
                  'LICHSGFIN',
                  'LT',
                  'LUPIN',
                  'M',
                  'MFIN',
                  'MANAPPURAM',
                  'MARICO',
                  'MARUTI',
                  'N',
                  'MCX',
                  'MFSL',
                  'MGL',
                  'MINDTREE',
                  'MOTHERSUMI',
                  'MRF',
                  'MRPL',
                  'MUTHOOTFIN',
                  'NATIONALUM',
                  'NBCC',
                  'NCC',
                  'NESTLEIND',
                  'NHPC',
                  'NIITTECH',
                  'NMDC',
                  'NTPC',
                  'OFSS',
                  'OIL',
                  'ONGC',
                  'ORIENTBANK',
                  'PAGEIND',
                  'PCJEWELLER',
                  'PEL',
                  'PETRONET',
                  'PFC',
                  'PIDILITIND',
                  'PNB',
                  'POWERGRID',
                  'PTC',
                  'PVR',
                  'RAMCOCEM',
                  'RAYMOND',
                  'RBLBANK',
                  'RCOM',
                  'RECLTD',
                  'RELCAPITAL',
                  'RELIANCE',
                  'RELINFRA',
                  'REPCOHOME',
                  'RNAVAL',
                  'RPOWER',
                  'SAIL',
                  'SBIN',
                  'SHREECEM',
                  'SIEMENS',
                  'SOUTHBANK',
                  'SREINFRA',
                  'SRF',
                  'SRTRANSFIN',
                  'STAR',
                  'SUNPHARMA',
                  'SUNTV',
                  'SUZLON',
                  'SYNDIBANK',
                  'TATACHEM',
                  'TATACOMM',
                  'TATAELXSI',
                  'TATAGLOBAL',
                  'TATAMOTORS',
                  'TATAMTRDVR',
                  'TATAPOWER',
                  'TATASTEEL',
                  'TCS',
                  'TECHM',
                  'TITAN',
                  'TORNTPHARM',
                  'TORNTPOWER',
                  'TV18BRDCST',
                  'TVSMOTOR',
                  'UBL',
                  'UJJIVAN',
                  'ULTRACEMCO',
                  'UNIONBANK',
                  'UPL',
                  'VEDL',
                  'VGUARD',
                  'VOLTAS',
                  'WIPRO',
                  'WOCKPHARMA',
                  'YESBANK',
                  'ZEEL'
                  }

one_day_data = 'TenMinDayData.csv';

file = open(one_day_data, "w")

for stock_name in fno_stock_list:
    stock_instu = upstox.get_instrument_by_symbol('NSE_EQ', stock_name)
    try:
        stock_data = upstox.get_ohlc(stock_instu, OHLCInterval.Minute_10,
                                     (datetime.today() - timedelta(365)).date(), datetime.today().date())
        if (len(stock_data) > 0):
            for stock in stock_data:
                var = stock_name + ',' + str(stock['volume']) + ',' + str(stock['open']) + ',' + str(
                    stock['high']) + ',' + str(
                    stock['low']) + \
                      ',' + str(stock['close']) + ',' + str(stock['cp']) + ',' + str(
                    datetime.fromtimestamp(int(stock['timestamp']) / 1000).strftime('%Y-%m-%d'))
                file.writelines(var)
                file.writelines('\n')

    except TypeError:
        pass





        # stock_instu = upstox.get_instrument_by_symbol('NSE_EQ', 'ACC')
        # stock_data = upstox.get_ohlc(stock_instu, OHLCInterval.Day_1,
        #                              (datetime.today() - timedelta(10)).date(), datetime.today().date())
        # print stock_data
        # print str(datetime.fromtimestamp(1515324531).strftime('%Y-%m-%d'))

        # file.close()
